import * as Utils from "./metadata/utils";
import {DecoratorType} from '../enums/decorator-type';
import {Decorators} from '../constants';

export function field(params?: {itemType?: any, primary?: boolean, autogenerated?: boolean, searchIndex?:boolean}) {
    return function (target: Object, propertyKey: string) {

        console.log('field - propertyKey: ', propertyKey, ', target:', target);
        Utils.addMetaData(target, Decorators.FIELD, DecoratorType.PROPERTY, params, propertyKey);
    }
}