import * as Utils from "./metadata/utils";

export function field(params?: {itemType?: any, primary?: boolean, autogenerated?: boolean}) {
    return function (target: Object, propertyKey: string) {

        console.log('field - propertyKey: ', propertyKey, ', target:', target);
        Utils.addMetaData(target, "field", Utils.DecoratorType.PROPERTY, params, propertyKey);
    }
}