import {field, document} from '../../mongoose/decorators'; 
import {Types} from 'mongoose';
import {CrudEntity} from '../../core/dynamic/crud.entity';

export class baseModel extends CrudEntity {
    constructor(object?: any) {
        super();
    }

    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    name: String;
}

export default baseModel;