import {field, document} from '../../mongoose/decorators'; 
import {Types} from 'mongoose';

export class baseModel {

    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    name: String;
}

export default baseModel;