import {onetomany, manytoone, manytomany} from '../../core/decorators';
import {document} from '../../mongoose/decorators/document';
import {field} from '../../mongoose/decorators/field';
import {IBlog} from './blog.ts';
import {Strict} from '../../mongoose/enums/document-strict';

@document({ name: 'blogs', strict: Strict.true  })
export class BlogModel{
    @field({primary: true, autogenerated: true})
    _id: any;
    
    @field()
    name: any;
    
    //@manytoone({rel: 'users'})
    //users: Array<UserModel>;

    constructor(blogDto: IBlog) {
        this._id = blogDto._id;
        this.name = blogDto.name;
    }
}
