import * as TM from './teachermodel';
import * as SM from './studentmodel';
import {onetomany, manytoone, manytomany, onetoone} from '../../core/decorators'; 
import {field, document} from '../../mongoose/decorators'; 
import {Types} from 'mongoose';
import {Strict} from '../../mongoose/enums/';

@document({ name: 'courses', strict: Strict.throw })
export class CourseModel {
    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    name: String;
}

export default CourseModel;