import {onetomany, manytoone, manytomany, jsonignore, required} from '../../core/decorators';
import {field, document} from '../../mongoose/decorators'; 
import {IRole} from './role';
import * as UM from './usermodel';
import {Strict} from '../../mongoose/enums/';
import {JsonIgnore} from '../../core/enums/jsonignore-enum';

@document({ name: 'roles', strict: Strict.false })
export class RoleModel{
    @field({primary: true, autogenerated: true})
    _id: any;
    
    @field()
    name: any;


    @field()
    @required()
    test: any;

    constructor(userDto: IRole) {
        this._id = userDto._id;
        this.name = userDto.name;
    }
}

export default RoleModel;