import * as StudentModel from './studentmodel';
import * as CourseModel from './coursemodel';
import {onetomany, manytoone, manytomany, onetoone} from '../../core/decorators';
import {field, document} from '../../mongoose/decorators';
import {Types} from 'mongoose';
import {Strict} from '../../mongoose/enums/';

@document({ name: 'teachers', strict: Strict.true })
export class TeacherModel {
    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    name: string;

    @field()
    age: number;

    @field()
    gender: string;

    @onetomany({ rel: 'courses', itemType: CourseModel, embedded: true })
    subjects: Array<CourseModel.CourseModel>;

    @onetomany({ rel: 'students', itemType: StudentModel, embedded: false, eagerLoading: true })
    students: Array<StudentModel.StudentModel>;
}

export default TeacherModel;