import Mongoose = require("mongoose");
import {Types} from 'mongoose';
import {Strict} from '../../mongoose/enums/';
import {field, document} from '../../mongoose/decorators'; 

@document({ name: 'blog', strict: Strict.throw })
export class blog{
   schema(): {} {
        return {
            '_id': Mongoose.Schema.Types.ObjectId,
            'name': String
        };
    }
   @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;
 
    @field()
    name: string;

}
export default blog;