import {Types} from 'mongoose';

//@document({ name: 'students', strict: Strict.true })
export class student {
    _id: Types.ObjectId;

    //@field()
    name: string;
    addresses: Array<string>;

    //@onetomany({ rel: 'subjects', itemType: subject, embedded: true })
    subjects: Array<subject>;
}

//@document({ name: 'subjects', strict: Strict.true })
export class subject {
    _id: string;
    name: string;
}

export class teacher {
    _id: string;
    name: string;
}

//@document({ name: 'divisions', strict: Strict.true })
export class division {
    //@field({ primary: true, autogenerated: true })
    _id: string;

    //@field()
    name: string;

    //@onetomany({ rel: 'students', itemType: student, embedded: true })
    students: Array<student>;
}