import {field, document, onetomany, manytoone, manytomany} from '../../decorators';
import {Strict} from '../../enums';
import {Types} from 'mongoose';

//@document({ name: 'students', strict: Strict.true })
export class student {
    //@field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    //@field()
    name: string;

    //@field({})
    addresses: Array<string>;

    //@onetomany({ rel: 'subjects', itemType: subject, embedded: true })
    subjects: Array<subject>;
}

//@document({ name: 'subjects', strict: Strict.true })
export class subject {
    //@field({ primary: true, autogenerated: true })
    _id: string;

    //@field()
    name: string;
}

//@document({ name: 'teachers', strict: Strict.true })
export class teacher {
    //@field({ primary: true, autogenerated: true })
    _id: string;

    //@field()
    name: string;
}

//@document({ name: 'divisions', strict: Strict.true })
export class division {
    //@field({ primary: true, autogenerated: true })
    _id: string;

    //@field()
    name: string;

    //@onetomany({ rel: 'students', itemType: student, embedded: true })
    students: Array<student>;
}