import {onetomany, manytoone, manytomany} from '../core/decorators';
import {field, document} from '../mongoose/decorators';
import {Strict} from '../mongoose/enums';

export class BaseModel {
    @field({ primary: true, autogenerated: true })
    _id: any;

    @field()
    name: any;
}

export default BaseModel;