import {field, document} from '../mongoose/decorators';
import {Types} from 'mongoose';
import {jsonignore} from '../core/decorators';

export class BaseEntity {
    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    name: String;

    @field({ itemType: String })
    courses: Array<String>;

    @field()
    email: String;

    @field()
    accessToken: String;

    @field()
    refreshToken: String;

    @field()
    password: String;
}

export default BaseEntity;