import {onetomany, manytoone, manytomany} from '../core/decorators';
import {field, document} from '../mongoose/decorators';
import {Strict} from '../mongoose/enums';

export class BaseModel {
    @field({ primary: true, autogenerated: true })
    _id: any;

    @field()
    name: any;

    /*
       nodedata internal use for caching, use for findWhere case
   */
    __selectedFindWhere: boolean;

    /*
        nodedata internal use for caching, to marked as partial load for findMany (egar load case not load)
    */
    __partialLoaded: boolean;
}

export default BaseModel;