import {onetomany, manytoone, manytomany} from '../decorators/association';
import {document} from '../decorators/document';
import {field} from '../decorators/field';

import {UserModel} from './usermodel';

@document({ name: 'roles' })
export class RoleModel{
    @field({isPrimary: true, isAutogenerated: true})
    _id: any;
    
    @field()
    name: string;
    
    @manytoone({rel: 'users'})
    users: Array<UserModel>;
}
