import {field, document, onetomany, manytoone, manytomany} from '../decorators'; 
import {IRole} from './role';
import * as UM from './usermodel';
import {Strict} from '../enums';

@document({ name: 'roles', strict: Strict.false })
export class RoleModel{
    @field({primary: true, autogenerated: true})
    _id: any;
    
    @field()
    name: any;
    
    //@manytoone({rel: 'users'})
    //users: Array<UserModel>;

    constructor(userDto: IRole) {
        this._id = userDto._id;
        this.name = userDto.name;
    }
}

export default RoleModel;