import {onetomany, manytoone, manytomany} from '../decorators/association';
import {document} from '../decorators/document';
import {field} from '../decorators/field';
import {IRole} from './role.ts';
import {UserModel} from './usermodel';

@document({ name: 'roles', isStrict: false })
export class RoleModel{
    @field({isPrimary: true, isAutogenerated: true})
    _id: any;
    
    @field()
    name: any;
    
    //@manytoone({rel: 'users'})
    //users: Array<UserModel>;

    constructor(userDto: IRole) {
        this._id = userDto._id;
        this.name = userDto.name;
    }
}
