import {onetomany, manytoone, manytomany} from '../core/decorators';
import {field, document} from '../mongoose/decorators';
import {Strict} from '../mongoose/enums';

@document({ name: 'stories', strict: Strict.true })
export class StoryModel {
    @field({ primary: true, autogenerated: true })
    _id: any;

    @field()
    name: any;   
}

export default StoryModel;