import * as TeacherModel from './teachermodel';
import * as CourseModel from './coursemodel';
import {field, document, onetomany, manytoone, manytomany, onetoone} from '../decorators';
import {IUser} from './user';
import {Types} from 'mongoose';
import {Strict} from '../enums';

@document({ name: 'students', strict: Strict.true })
export class StudentModel {
    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    name: string;

    @field()
    age: number;

    @field()
    gender: string;

    @manytomany({ rel: 'courses', itemType: CourseModel, embedded: true })
    subjects: Array<CourseModel.CourseModel>;

    @onetoone({ rel: 'courses', itemType: CourseModel, embedded: true})
    mainSubjects: CourseModel.CourseModel;
}

export default StudentModel;