import * as RM from './rolemodel';
import {field, document, onetomany, manytoone, manytomany} from '../decorators'; 
import {IUser} from './user';
import {Types} from 'mongoose';
import {Strict} from '../enums';
import * as r from './rolemodel';

@document({ name: 'users', strict: Strict.false })
export class UserModel {
    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    name: string;

    @field({ itemType: String})
    courses: Array<string>;

    @field()
    email: string;

    @field()
    accessToken: string;

    @field()
    refreshToken: string;

    @field()
    password: string;

    @field()
    age: string;

    @onetomany({ rel: 'roles', itemType: RM, embedded: true })
    roles: Array<RM.RoleModel>;

    _links: any;  
    
    // constructor(){
    //     this._id=0;
    //     this.name="";
    //     this.roles=new Array<RoleModel>();
    // }
    constructor(userDto: IUser) {
        this._links = {};
        this._id = <any>userDto._id;
        this.name = userDto.name;
        //this.age = userDto.age;
        //this.password = userDto.password;
        //this.email = userDto.email;
        if (userDto.roles)
            this.roles = userDto.roles;
        else
            this.roles = new Array<RM.RoleModel>();
    }
}

export default UserModel;